echo " arguments total : $# "
echo " script name : $0 "
echo " script 1st argument : $1 "
echo " script 2nd argument : $2 "
echo " script 3rd argument : $3 "
echo " list of all arguments : * $* "
echo " list of all arguments : @ $@ "
echo " PID of shell : $$ "
